# Generated by Django 5.1.4 on 2025-03-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',)},
        ),
    ]
