# Generated by Django 5.1.4 on 2025-06-02 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_curriculum_curriculumsubject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumsubject',
            options={'ordering': ['semester', 'subject__name'], 'verbose_name': 'Дисциплина учебного плана', 'verbose_name_plural': 'Дисциплины учебного плана'},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='curriculum_pdfs/', verbose_name='PDF учебного плана'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='total_credits',
            field=models.FloatField(default=0, verbose_name='Общее количество кредитов'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательная дисциплина'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='post',
            name='credit_diff_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные сравнения кредитов'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный план'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='posts.specialty', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='year',
            field=models.IntegerField(verbose_name='Год плана'),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='credits',
            field=models.FloatField(verbose_name='Кредиты'),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.subject', verbose_name='Дисциплина'),
        ),
    ]
