# Generated by Django 5.1.4 on 2025-04-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='post',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='posts.specialty', verbose_name='Приоритетные специальности'),
        ),
    ]
