# Generated by Django 5.1.4 on 2025-04-16 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='current_approver',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status_approval',
        ),
    ]
