# Generated by Django 5.1.4 on 2025-04-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_cours_post_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='protocol_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер протокола'),
        ),
    ]
