# Generated by Django 5.1.4 on 2025-06-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_curriculumsubject_options_curriculum_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='окуу план(PDF/скан)'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='short_name',
            field=models.CharField(default=1, max_length=10, verbose_name='кыскартылган адистиктин аталышы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=20, verbose_name='адистиктин коду'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='адистиктин аталышы'),
        ),
    ]
