# Generated by Django 5.1.4 on 2025-04-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_current_approver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalstep',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='comment',
        ),
    ]
