# Generated by Django 5.1.4 on 2025-05-16 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_protocol_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curriculum_file',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/', verbose_name='Окуу планы (PDF)'),
        ),
        migrations.AlterField(
            model_name='postsubject',
            name='credits',
            field=models.FloatField(verbose_name='Кредиты по заявлению'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(verbose_name='Семестр')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Кредиты')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='posts.specialty', verbose_name='Специальность')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.subject', verbose_name='Дисциплина')),
            ],
        ),
    ]
