# Generated by Django 5.1.4 on 2025-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_specialties_post_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/', verbose_name='Заявление студента (PDF/скан)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Сгенерированный протокол (PDF)'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
