# Generated by Django 5.1.4 on 2025-06-04 05:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_specialty_pdf_file_specialty_short_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_file', models.FileField(upload_to='specialty_transcripts/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл транскрипта (PDF)')),
                ('specialty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='posts.specialty', verbose_name='Специальность')),
            ],
        ),
    ]
