# Generated by Django 5.1.4 on 2025-05-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_curriculum_file_alter_postsubject_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='curriculum_file',
        ),
        migrations.AddField(
            model_name='specialty',
            name='curriculum_file',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/', verbose_name='Окуу планы (PDF)'),
        ),
        migrations.AlterField(
            model_name='postsubject',
            name='credits',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
