# Generated by Django 5.1.4 on 2025-04-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_application_file_alter_post_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='application_file',
        ),
    ]
