# Generated by Django 5.1.4 on 2025-05-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_curriculum_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Укороченная название'),
        ),
    ]
