# Generated by Django 5.1.4 on 2025-05-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_specialty_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/', verbose_name='Транскрипт / Академическая справка (PDF)'),
        ),
    ]
