# Generated by Django 5.1.4 on 2025-05-21 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_transcript_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.FloatField(verbose_name='Кредиттер')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognized_credits', to='posts.post')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('from_specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='posts.specialty')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='posts.post')),
                ('to_specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='posts.specialty')),
            ],
        ),
    ]
