# Generated by Django 5.1.4 on 2025-05-22 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_recognizedcredit_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='from_specialty',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='post',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_specialty',
        ),
        migrations.AddField(
            model_name='post',
            name='specialty_diff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_diff_posts', to='posts.specialty', verbose_name='Специальность (Айырмачылык)'),
        ),
        migrations.DeleteModel(
            name='RecognizedCredit',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
