# Generated by Django 5.1.4 on 2025-05-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_transfer_from_specialty_remove_transfer_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsubject',
            name='is_recognized',
            field=models.BooleanField(default=False),
        ),
    ]
