# Generated by Django 5.1.4 on 2025-05-23 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postsubject_is_recognized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='specialty_diff',
        ),
        migrations.RemoveField(
            model_name='postsubject',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='postsubject',
            name='is_recognized',
        ),
        migrations.AddField(
            model_name='postsubject',
            name='earned_credits',
            field=models.FloatField(default=0, verbose_name='Полученные кредиты'),
        ),
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.FloatField(default=0, verbose_name='Кредит'),
        ),
        migrations.AddField(
            model_name='subject',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.specialty', verbose_name='Специальность'),
        ),
    ]
